# Generated by Django 3.2.25 on 2025-07-24 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='任务描述')),
                ('date', models.DateField(verbose_name='截止日期')),
                ('priority', models.CharField(choices=[('High', '高'), ('Medium', '中'), ('Low', '低')], default='Medium', max_length=10, verbose_name='优先级')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
